allowBuilds:
  electron: true
  electron-winstaller: true
onlyBuiltDependencies:
  - electron
  - electron-winstaller

overrides:
  "@electron/get>undici": ^7.28.0
  node-gyp>undici: ^6.27.0
  form-data: ^4.0.6
  tar: ^7.5.16
